### ISSUE TITLE
Investigate negative number of peers to dial

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/celestia-core#2164]
When running a 97 validators network, this log shows up:
```
12:18PM INF Ensure peers module=pex numDialing=0 numInPeers=38 numOutPeers=12 numToDial=-2
12:21PM INF Ensure peers module=pex numDialing=0 numInPeers=40 numOutPeers=12 numToDial=-2
```

The number of peers to dial is `-2` which looks invalid to me. We need to investigate it.

**Comment by rach-id** [comment]
Also, in a 20 validators network, we have:
```
8:28AM INF Ensure peers module=pex numDialing=0 numInPeers=14 numOutPeers=5 numToDial=5
```
`numToDial` is invalid.

**Comment by rach-id** [comment]
this seems to be related to #2029, @ninabarbakadze why did we multiply the number of peers to be dialed by 4:
https://github.com/celestiaorg/celestia-core/blob/bfc33c731322f8b65466a76a2b79fad295b47a3b/p2p/pex/pex_reactor.go#L464

instead of using the value from the config? Then, we can set a bigger default value to it, and also ask node operators to increase that value when we want.

**Comment by ninabarbakadze** [comment]
It shows negative number by how many peers we're over the limit. Calculations should be fixed. I can address them.

> this seems to be related to https://github.com/celestiaorg/celestia-core/pull/2029, @ninabarbakadze why did we multiply the number of peers to be dialed by 4:

If you look at the PEX reactor both historically and currently you'll notice a lot of hardcoded magic numbers in the peering logic. This is one of those values we arrived at through testing. The number 40 seemed like a balance where it gave us a good rate of peer discovery with 10 second intervals otherwise it was too slow. The reason this worked is because the address book stores all known addresses, including inactive peers. During the dialing process, we attempt connections to many peers including the inactive ones until some of them eventually respond.

To make this behavior more dynamic and less arbitrary, I was thinking about implementing progressive dialing. The idea is to initiate dials based on how many peers we still need, using a 2-second cadence and following the toDial calculation until we fill all the spots. This would adaptively scale the dialing rate, improve clarity, and remove the need for tuning magic numbers like 40.

> instead of using the value from the config? 

Do you mean create a new value in config?

**Comment by rach-id** [comment]
Hum, I see. Is 40 supposed to be a constant? Because if I increase the number of out peer in the config, which is currently 10 = 40 / 4, if I set it to 20 = 80 / 4, we should expect to connect to 80 peers?

**Comment by ninabarbakadze** [comment]
> Hum, I see. Is 40 supposed to be a constant? Because if I increase the number of out peer in the config, which is currently 10 = 40 / 4, if I set it to 20 = 80 / 4, we should expect to connect to 80 peers?

No, I don't see 40 as a constant. We have a max number of outbound peers we want to linger around which is currently 10. If we wanted to increase numOutboundPeers we would have to reconsider how many peers we're dialling. We could make it a constant or we can do progressive dialling.

**Comment by rach-id** [comment]
I still don't fully get it, so if I set the number of outbound peers to 10, how many should I expect to be connected to?

**Comment by ninabarbakadze** [comment]
If you set the number of outbound peers to 10, the node will try to reach and then keep _**around**_ 10 active outbound connections. During discovery, it dials more (up to 40 because of the *4 multiplier) to find good peers quickly since the address book is full of peers that do not respond. Before going to the loop of dialing, we always check if we’ve hit the target of 10 peers, but sometimes we go a bit over which isn’t a problem and that’s why you might see something like numToDial = -2 which should get fixed fwiw. It just means we already have a couple more peers than needed. Also, just a heads up it really helps to ask these kinds of questions during the PR review, so we can catch and clarify things while everything’s still easily modifiable.

**Comment by rach-id** [comment]
thanks for the clarification. So I guess this issue can be closed, it's fine to have a negative number of peers to dial. We might document it somewhere at some point, but it is expected and totally fine to have.

**Comment by rach-id** [comment]
As per sync discussion, this issue can be about improving the logs to mention the number of extra peers and the number of peers to dial
